# Generated by Django 4.1.4 on 2023-01-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBmanageApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="sPhoneAuth",
            field=models.BooleanField(default=False),
        ),
    ]
