# Generated by Django 4.1.4 on 2023-01-05 04:25

import DBmanageApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBmanageApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="sUserID",
            field=models.CharField(
                default=DBmanageApp.models.UserUUID,
                editable=False,
                max_length=43,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
