# Generated by Django 4.1.4 on 2023-01-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBmanageApp", "0002_userdata_sphoneauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="sEmail",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
