# Generated by Django 4.1.4 on 2023-01-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBmanageApp", "0003_userdata_semail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="sPhone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
