# Generated by Django 4.1.4 on 2023-01-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMSrecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SID", models.CharField(max_length=36, null=True)),
                ("SPhone", models.CharField(max_length=10)),
                ("STime", models.DateTimeField(auto_now_add=True)),
                ("SCode", models.CharField(max_length=4, null=True)),
            ],
            options={
                "verbose_name": "簡訊認證紀錄",
                "verbose_name_plural": "簡訊認證紀錄",
            },
        ),
    ]
