# Generated by Django 4.1.4 on 2023-01-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SMSloginApp", "0002_smsrecord_sid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsrecord",
            name="SVerified",
        ),
    ]
