# Generated by Django 4.1.4 on 2022-12-30 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "sUserID",
                    models.CharField(
                        default=uuid.UUID("8aaf5b5e-8858-11ed-b228-d6fe501fc464"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sLineID", models.CharField(max_length=33, null=True)),
                ("sAccount", models.CharField(max_length=20, null=True)),
                ("sPassword", models.CharField(max_length=20, null=True)),
                ("sName", models.CharField(max_length=30, null=True)),
                ("sPhone", models.CharField(max_length=20, null=True)),
            ],
            options={
                "verbose_name": "客戶個人資料",
                "verbose_name_plural": "客戶個人資料",
            },
        ),
    ]
