# Generated by Django 4.1.4 on 2023-01-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LineLoginApp", "0002_userdata_spictureurl_alter_userdata_saccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="sAddress",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="sNickName",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="sName",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
