# Generated by Django 4.1.4 on 2023-01-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LineLoginApp", "0003_userdata_saddress_userdata_snickname_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
