# Generated by Django 4.1.4 on 2023-01-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auth_token",
            fields=[
                (
                    "Agroup",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("Atoken", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="REST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RSMSget", models.CharField(max_length=36, null=True)),
                ("Rstate", models.CharField(max_length=36, null=True)),
                ("RTime", models.DateTimeField(auto_now_add=True)),
                ("SCode", models.CharField(max_length=4, null=True)),
            ],
            options={
                "verbose_name": "RESTapi要求紀錄",
                "verbose_name_plural": "RESTapi要求紀錄",
            },
        ),
    ]
