# Generated by Django 4.1.4 on 2023-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineAPI_record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Rstate",
                    models.CharField(
                        max_length=36, null=True, verbose_name="網址state辨識碼(用以二次請求)"
                    ),
                ),
                (
                    "RstateUsed",
                    models.BooleanField(
                        default=False, verbose_name="請求UserID與否(第二次握手)"
                    ),
                ),
                (
                    "RlineID",
                    models.CharField(
                        max_length=33, null=True, verbose_name="line伺服器回傳的lineID"
                    ),
                ),
                (
                    "Rtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="第一次請求網址時間"),
                ),
                (
                    "Rbackurl",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="用戶要求line後返回網址",
                    ),
                ),
            ],
            options={
                "verbose_name": "LineLogin_API 要求紀錄",
                "verbose_name_plural": "LineLogin_API 要求紀錄",
            },
        ),
    ]
