# Generated by Django 4.1.4 on 2023-01-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="getLineURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rstate", models.CharField(max_length=36, null=True)),
                ("RTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Line Login URL 要求紀錄",
                "verbose_name_plural": "Line Login URL 要求紀錄",
            },
        ),
        migrations.CreateModel(
            name="getPK_Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rstate", models.CharField(max_length=36, null=True)),
                ("RTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "PK by Line login 要求紀錄",
                "verbose_name_plural": "PK by Line login 要求紀錄",
            },
        ),
        migrations.DeleteModel(
            name="Auth_token",
        ),
        migrations.DeleteModel(
            name="REST",
        ),
    ]
