# Generated by Django 4.1.4 on 2023-01-04 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineapi_record",
            name="Rstate",
            field=models.CharField(
                default=uuid.UUID("d0a3fb95-b935-4259-b109-36fe7f933e95"),
                max_length=36,
                verbose_name="網址state辨識碼(用以二次請求)",
            ),
        ),
    ]
