# Generated by Django 4.1.4 on 2023-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0002_alter_lineapi_record_rstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineapi_record",
            name="Rstate",
            field=models.CharField(max_length=36, verbose_name="網址state辨識碼(用以二次請求)"),
        ),
    ]
