# Generated by Django 4.1.4 on 2023-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0003_alter_lineapi_record_rstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineapi_record",
            name="RlineID",
        ),
        migrations.AddField(
            model_name="lineapi_record",
            name="RuserID",
            field=models.CharField(
                max_length=36, null=True, verbose_name="個資系統判定的使用者ID"
            ),
        ),
    ]
