# Generated by Django 4.1.4 on 2023-01-05 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0004_remove_lineapi_record_rlineid_lineapi_record_ruserid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineapi_record",
            name="id",
        ),
        migrations.AlterField(
            model_name="lineapi_record",
            name="Rstate",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="網址state辨識碼(用以二次請求)",
            ),
        ),
    ]
