# Generated by Django 4.1.4 on 2023-01-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0005_remove_lineapi_record_id_alter_lineapi_record_rstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineapi_record",
            name="Rstate",
            field=models.CharField(
                default="State-0f90e89e-a0bd-468d-94f5-2900c515b6fb",
                editable=False,
                max_length=42,
                primary_key=True,
                serialize=False,
                verbose_name="網址state辨識碼(用以二次請求)",
            ),
        ),
    ]
