# Generated by Django 4.1.4 on 2023-01-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RESTapiApp", "0007_accessapi_record_smsapi_record_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsapi_record",
            name="Rphone",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="accessapi_record",
            name="Raccess_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="授權碼啟用時間"),
        ),
        migrations.AlterField(
            model_name="lineapi_record",
            name="Rbackurl",
            field=models.CharField(
                max_length=200, null=True, verbose_name="用戶要求line後返回的絕對網址"
            ),
        ),
        migrations.AlterField(
            model_name="lineapi_record",
            name="RstateUsed",
            field=models.BooleanField(
                default=False, verbose_name="用以請求UserID與否(第二次握手)"
            ),
        ),
        migrations.AlterField(
            model_name="smsapi_record",
            name="RSMS_code",
            field=models.CharField(max_length=4, null=True, verbose_name="該次簡訊驗證碼"),
        ),
        migrations.AlterField(
            model_name="smsapi_record",
            name="RSMSid",
            field=models.CharField(
                max_length=42,
                primary_key=True,
                serialize=False,
                verbose_name="要求辨識碼(用以二次請求)",
            ),
        ),
    ]
